language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

jobs:
    include:
        - stage: build
        - script: ./build python main.py &
        - stage: test
        - script: ./test python auto_test.py