language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    - mysql -u root < bdd/script_sql/create_database.sql
    - |
      python main.py unit_test &
      APP_PID=$!
    - python unit_test/user/launcher.py
    #- curl -X POST "http://127.0.0.1:5000/api/user/" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"gender\": 0, \"lastname\": \"Doe\", \"firstname\": \"John\", \"mail\": \"john@doe.com\", \"password\": \"password\", \"country\": \"France\", \"town\": \"Lille\", \"street\": \"rue nationale\", \"street_number\": \"13\", \"region\": \"Hauts de france\", \"postal_code\": \"123456\"}"
    - kill $APP_PID