language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    - mysql -u root < bdd/script_sql/create_database.sql
    # export project to pythonpath for module importation
    - export PYTHONPATH=$PYTHONPATH:$PWD
    # start API
    - |
      python main.py unit_test &
      APP_PID=$!
    - python unit_test/product/tests/tests_post.py
    - python unit_test/product/tests/tests_get.py
#    - curl $NGROK_URL
#    - curl $NGROK_URL/api

    - kill $APP_PID