language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

script:
    - echo "Unit Test"

after_script:
    - |
      python main.py &
      APP_PID=$!
    - sleep 5
    - python auto_test.py
    - kill $APP_PID