language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    - mysql -u root < bdd/script_sql/create_database.sql
    - pwd
    - export PYTHONPATH=$PYTHONPATH:./unit_test
    # start API
    - |
      python main.py unit_test &
      APP_PID=$!
# TODO trouver comment fonctionne test uni sur pycharm pour pas avoir probleme d'import lors execution travis
    - python unit_test/user/tests/tests_post.py
#    - curl $NGROK_URL
#    - curl $NGROK_URL/api

    - kill $APP_PID