language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    # create database
    - mysql -u root < bdd/script_sql/create_database.sql
    - mysql -u root < bdd/script_sql/08_01_2020.sql
    - mysql -u root < bdd/script_sql/22_04_2020.sql

    # export project to pythonpath for module importation
    - export PYTHONPATH=$PYTHONPATH:$PWD

    # start API
    - |
      python main.py unit_test &
      APP_PID=$!
    - sleep 2

    # Test user route
    - python unit_test/user/tests/tests_post.py
    - python unit_test/user/tests/tests_delete.py
    - python unit_test/user/tests/tests_put.py

    # Test product route
    - python unit_test/product/tests/tests_post.py
    - python unit_test/product/tests/tests_get.py
    - python unit_test/product/tests/tests_delete.py

    # Test token
    - python unit_test/oauth/tests/test_token.py

    - kill $APP_PID