language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    - mysql -u root < bdd/script_sql/07-01-2019.sql
    - |
      python main.py &
      APP_PID=$!
    #- python auto_test.py (unitest)
    - kill $APP_PID