language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

script:
    - |
      python main.py &
      APP_PID=$!
    - python automated_tests/auto_test.py
    - kill $APP_PID