language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

jobs:
    include:
        - stage: api
        - script:
            - python main.py
        - script:
            - python auto_test.py