language: python
python:
    - "3.7.1"

install:
    - pip install --upgrade pip
    - pip install --upgrade -r requirements.txt

services:
  - mysql

script:
    - mysql -u root < bdd/script_sql/create_database.sql
    # start API
    - |
      python main.py unit_test &
      APP_PID=$!

    - python unit_test/user/launcher.py
#    - curl $NGROK_URL
#    - curl $NGROK_URL/api

    - kill $APP_PID