version: "1.0"
build: "__BUILD_NUMBER__"
environment: "development"
oauth:
    grant_type:
        - client_credentials
        - authorization_code
        - password
        - refresh_token
    token_ttl: 3600
    refresh_token_ttl: 604800
mongodb:
    uri: "mongodb://localhost:27017/Arlex"
mysql:
    uri: "mysql://2021_arlex:meug0Ail8@db-etud.labeip.local:3306/2021_arlex"
